### ISSUE TITLE
Ny bättre bana

### ISSUE THREAD

**Issue by antoncarlsson** [fsandelin/datakom#13]
Hade varit snyggt att ha någon lite mer komplex bana att visa på demon.

**Comment by falapen** [comment]
Y u h8 my awesome map!!

**Comment by fsandelin** [comment]
Ett förslag är att göra en till som den byter till när man vinner som sedan byter tillbaka så det blir rotation mellan dem

**Comment by antoncarlsson** [comment]
Klar, ligger i Anton-branchen.
