### ISSUE TITLE
När en tredje/fjärde etc joinar får de förgående klienterna inte den infon

### ISSUE THREAD

**Issue by fsandelin** [fsandelin/datakom#15]
Förslag på lösningar: 
1. Sätt upp en "RMI server" hos klienten så servern kan anropa den 
2. Skicka med antal spelare i varje UDP packet och om det är ett annorlunda nummer än vad som var förväntat så kan de fråga servern efter nya uppdateringar.

Föreslår lösning nr.2.

**Comment by CasparLindvall** [comment]
nr. 2 låter vettigt!

EDIT: tog bort hashtaggen då den referera till något annat

**Comment by falapen** [comment]
Röstar också på nr 2 så slipper man köra en till rmiserver

**Comment by fsandelin** [comment]
Updatering: Lösning finns på Fredrik branschen. Återstår att testa det.

**Comment by fsandelin** [comment]
Solved in latest master merge
