### ISSUE TITLE
Hostens karaktär blir den andras.

### ISSUE THREAD

**Issue by CasparLindvall** [fsandelin/datakom#19]
Efter att en client connectar så "hoppar" hosten till clienten och blir samma spelare. Hosten kan nu inte gå själv (men försöker), däremot kan clienten röra sig som vanligt. Osäker om det är virtualbox som spökar då Anton (och antar ni andra två) inte har detta problem.

**Comment by fsandelin** [comment]
använd de utkommenderade debug printsen för att kolla vad du får för värden från UDP

**Comment by fsandelin** [comment]
Testa också "rm -rf datakom" när du står utanför repot och clona nytt git repo.

**Comment by CasparLindvall** [comment]
TODO: mutex kring RMI relaterat

**Comment by fsandelin** [comment]
Fixat, Servern ignorerar nu mera clients som påstår vara servern. Händer när klienten tror att den har ID 0 istället för något annat. Utöver det så borde en client aldrig kunna få ID 0.

Mera problem med trust the client finns i issue #26
