### ISSUE TITLE
Spelarnas position uppdateras inte

### ISSUE THREAD

**Issue by antoncarlsson** [fsandelin/datakom#4]
Gissning: för att spelarna inte får korrekta x och y värden.
Ledtråd: "Client received | 0 0" på klienten när man kör spelet.

**Comment by fsandelin** [comment]
Datagram trådarna är utdaterade och en lyssnande tråd uppdaterar ingenting i GameThread just nu. Detta till sammans med #5 förväntas fixas efter mera jobb på Datagram tråden

**Comment by fsandelin** [comment]
Löst i senaste uppdateringen i comms
