### ISSUE TITLE
Null Pointer Exception i klienten

### ISSUE THREAD

**Issue by antoncarlsson** [fsandelin/datakom#5]
Upprepade java.lang.NullPointerException när man som klient ansluter till en host. Antagligen relaterat till issue #4.

**Comment by CasparLindvall** [comment]
Om man printar de mottagna värdena i DatagramClientThread ser man att vi skickar ingenting väldigt ofta. Man kan begränsa run() hastigheten (se mitten: http://blog.slapware.eu/game-engine/programming/multithreaded-renderloop-part1/) så minskas nullpointers till ~1/2. Osäker om vi har pålitlig connection via valda portarna. Ska undersöka mer imorgon

**Comment by fsandelin** [comment]
Detta är löst i senaste uppdateringen hos branschen comms
