### ISSUE TITLE
Kommandoradsargument

### ISSUE THREAD

**Issue by antoncarlsson** [fsandelin/datakom#7]
Hade varit smidigare med kommandoradsargument som man skickar med direkt när man startar spelet istället för att behöva skriva in varje sak för sig. Exempel: `java Game 1099 1 127.0.0.1`

**Comment by CasparLindvall** [comment]
Fixar alt. test-körning uppe om 5

**Comment by fsandelin** [comment]
ligger uppe i comms

Kör "java Game 1 1" t.ex. för att få upp usage meddelande
